### ISSUE TITLE
Cannot render documents due to Hint compilation error

### ISSUE THREAD

**Issue by Simre1** [brandonchinn178/templette#8]
Hello!

I have tried to run one of the examples but I sadly get an error:
```
cabal run templette-markdown -- --render examples/readme-snippet.md
```
Fails due to a compilation error:
```
templette-markdown: WontCompile [GhcError {errMsg = "/tmp/templette-render15220-0.hs:1:1: error:\n    Could not find module \8216Templette.Prelude\8217\n    Use -v (or `:set -v` in ghci) to see a list of the files searched for."},GhcError {errMsg = "/tmp/templette-render15220-0.hs:2:1: error:\n    Could not find module \8216Templette.Markdown.Prelude\8217\n    Use -v (or `:set -v` in ghci) to see a list of the files searched for."}]
```

I have found some info on the [hint github page](https://github.com/haskell-hint/hint#limitations) which might be the cause:
> Importing a module from the current package is not supported. It might look like it works on one day and then segfault the next day. You have been warned.

The advised fix from the _hint README_ is:
> To work around this limitation, move those modules to a separate package. Now the part of your code which calls hint and the code interpreted by hint can both import that module.

**Comment by Simre1** [comment]
Seems to me like the executable and the library should count as separate packages, so I am unsure if the hint limitation I mentioned is the cause of the problem.

**Comment by brandonchinn178** [comment]
Cabal might not set up the environment correctly. Can you try `cabal exec ...`?

**Comment by Simre1** [comment]
That worked, thanks for the quick reply! I never knew that `cabal run` and `cabal exec` run the executable differently.

**Comment by brandonchinn178** [comment]
Yeah, it's unfortunate, and hopefully #4 will make the situation better

But FYI: `cabal run` just finds the built executable and runs it plainly, `cabal exec` does the same thing but also sets environment variables and such
